# Generated by Django 5.2.4 on 2025-07-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_client_owner_alter_mailing_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [("can_manage_client", "Может управлять клиентами")]
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_manage_mailing", "Может управлять рассылками")]
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_manage_message", "Может управлять сообщениями")]
            },
        ),
    ]
